import {
  IconBrandAirbnb,
  IconBrandAmazon,
  IconBrandAppstore,
  IconBrandBandcamp,
  IconBrandBehance,
  IconBrandBlogger,
  IconBrandBluesky,
  IconBrandBumble,
  IconBrandDeviantart,
  IconBrandDiscord,
  IconBrandDribbble,
  IconBrandFacebook,
  IconBrandFiverr,
  IconBrandFlipboard,
  IconBrandGithub,
  IconBrandGooglePlay,
  IconBrandGrindr,
  IconBrandInstagram,
  IconBrandKick,
  IconBrandLinkedin,
  IconBrandMedium,
  IconBrandMessenger,
  IconBrandOnlyfans,
  IconBrandPatreon,
  IconBrandPaypal,
  IconBrandPinterest,
  IconBrandProducthunt,
  IconBrandReddit,
  IconBrandSlack,
  IconBrandSnapchat,
  IconBrandSoundcloud,
  IconBrandSpotify,
  IconBrandTelegram,
  IconBrandThreads,
  IconBrandTiktok,
  IconBrandTripadvisor,
  IconBrandTumblr,
  IconBrandTwitch,
  IconBrandVimeo,
  IconBrandWechat,
  IconBrandWhatsapp,
  IconBrandWordpress,
  IconBrandX,
  IconBrandYoutube,
  IconGlobe,
  IconMail,
  IconPhone,
} from '@tabler/icons-react'

export const SOCIAL_ICONS = {
  EMAIL: {
    label: 'Email',
    icon: IconMail,
    domain: 'mailto:',
  },
  PHONE: {
    label: 'Phone',
    icon: IconPhone,
    domain: 'tel:',
  },
  WEBSITE: {
    label: 'Website',
    icon: IconGlobe,
    domain: undefined,
  },
  AMAZON: {
    label: 'Amazon',
    icon: IconBrandAmazon,
    domain: 'amazon.com',
  },
  APPSTORE: {
    label: 'App Store',
    icon: IconBrandAppstore,
    domain: 'apps.apple.com',
  },
  GOOGLEPLAY: {
    label: 'Google Play',
    icon: IconBrandGooglePlay,
    domain: 'play.google.com',
  },
  BLOGGER: {
    label: 'Blogger',
    icon: IconBrandBlogger,
    domain: 'blogger.com',
  },
  INSTAGRAM: {
    label: 'Instagram',
    icon: IconBrandInstagram,
    domain: 'instagram.com',
  },
  BLUESKY: {
    label: 'BlueSky',
    icon: IconBrandBluesky,
    domain: 'bluesky.app',
  },
  FACEBOOK: {
    label: 'Facebook',
    icon: IconBrandFacebook,
    domain: 'facebook.com',
  },
  X: {
    label: 'X',
    icon: IconBrandX,
    domain: 'x.com',
  },
  LINKEDIN: {
    label: 'LinkedIn',
    icon: IconBrandLinkedin,
    domain: 'linkedin.com',
  },
  TIKTOK: {
    label: 'TikTok',
    icon: IconBrandTiktok,
    domain: 'tiktok.com',
  },
  YOUTUBE: {
    label: 'YouTube',
    icon: IconBrandYoutube,
    domain: 'youtube.com',
  },
  PINTEREST: {
    label: 'Pinterest',
    icon: IconBrandPinterest,
    domain: 'pinterest.com',
  },
  SNAPCHAT: {
    label: 'Snapchat',
    icon: IconBrandSnapchat,
    domain: 'snapchat.com',
  },
  REDDIT: {
    label: 'Reddit',
    icon: IconBrandReddit,
    domain: 'reddit.com',
  },
  TUMBLR: {
    label: 'Tumblr',
    icon: IconBrandTumblr,
    domain: 'tumblr.com',
  },
  WHATSAPP: {
    label: 'WhatsApp',
    icon: IconBrandWhatsapp,
    domain: 'whatsapp.com',
  },
  TELEGRAM: {
    label: 'Telegram',
    icon: IconBrandTelegram,
    domain: 'telegram.org',
  },
  MESSENGER: {
    label: 'Messenger',
    icon: IconBrandMessenger,
    domain: 'messenger.com',
  },
  WECHAT: {
    label: 'WeChat',
    icon: IconBrandWechat,
    domain: 'wechat.com',
  },
  DISCORD: {
    label: 'Discord',
    icon: IconBrandDiscord,
    domain: 'discord.com',
  },
  SLACK: {
    label: 'Slack',
    icon: IconBrandSlack,
    domain: 'slack.com',
  },
  TWITCH: {
    label: 'Twitch',
    icon: IconBrandTwitch,
    domain: 'twitch.tv',
  },
  PATEON: {
    label: 'Patreon',
    icon: IconBrandPatreon,
    domain: 'patreon.com',
  },
  ONLYFANS: {
    label: 'OnlyFans',
    icon: IconBrandOnlyfans,
    domain: 'onlyfans.com',
  },
  GRINDR: {
    label: 'Grindr',
    icon: IconBrandGrindr,
    domain: 'grindr.com',
  },
  BUMBLE: {
    label: 'Bumble',
    icon: IconBrandBumble,
    domain: 'bumble.com',
  },
  MEDIUM: {
    label: 'Medium',
    icon: IconBrandMedium,
    domain: 'medium.com',
  },
  GITHUB: {
    label: 'GitHub',
    icon: IconBrandGithub,
    domain: 'github.com',
  },
  BEHANCE: {
    label: 'Behance',
    icon: IconBrandBehance,
    domain: 'behance.net',
  },
  DRIBBLE: {
    label: 'Dribbble',
    icon: IconBrandDribbble,
    domain: 'dribbble.com',
  },
  SOUNDCLOUD: {
    label: 'SoundCloud',
    icon: IconBrandSoundcloud,
    domain: 'soundcloud.com',
  },
  BANDCAMP: {
    label: 'Bandcamp',
    icon: IconBrandBandcamp,
    domain: 'bandcamp.com',
  },
  DEVIANTART: {
    label: 'DeviantArt',
    icon: IconBrandDeviantart,
    domain: 'deviantart.com',
  },
  PRODUCT_HUNT: {
    label: 'Product Hunt',
    icon: IconBrandProducthunt,
    domain: 'producthunt.com',
  },
  FLIPBOARD: {
    label: 'Flipboard',
    icon: IconBrandFlipboard,
    domain: 'flipboard.com',
  },
  TRIPADVISOR: {
    label: 'TripAdvisor',
    icon: IconBrandTripadvisor,
    domain: 'tripadvisor.com',
  },
  AIRBNB: {
    label: 'Airbnb',
    icon: IconBrandAirbnb,
    domain: 'airbnb.com',
  },
  FIVERR: {
    label: 'Fiverr',
    icon: IconBrandFiverr,
    domain: 'fiverr.com',
  },
  VIMEO: {
    label: 'Vimeo',
    icon: IconBrandVimeo,
    domain: 'vimeo.com',
  },
  WORDPRESS: {
    label: 'WordPress',
    icon: IconBrandWordpress,
    domain: 'wordpress.com',
  },
  PAYPAL: {
    label: 'PayPal',
    icon: IconBrandPaypal,
    domain: 'paypal.com',
  },
  SPOTIFY: {
    label: 'Spotify',
    icon: IconBrandSpotify,
    domain: 'spotify.com',
  },
  KICK: {
    label: 'Kick',
    icon: IconBrandKick,
    domain: 'kick.com',
  },
  THREADS: {
    label: 'Threads',
    icon: IconBrandThreads,
    domain: 'threads.com',
  },
} as const
